import {
  hotel1,
  hotel10,
  hotel11,
  hotel12,
  hotel13,
  hotel14,
  hotel15,
  hotel16,
  hotel17,
  hotel18,
  hotel19,
  hotel2,
  hotel20,
  hotel21,
  hotel22,
  hotel3,
  hotel4,
  hotel5,
  hotel6,
  hotel7,
  hotel8,
  hotel9,
} from "../assets";

export const listRooms = [
  {
    name: "Habitación Doble Estándar",
    bed: "Cama doble",
    capacityPeople: 1,
    roomView: "Vista a la ciudad",
    services: ["Caja fuerte", "Aire acondicionado", "Minibar"],
    modCons: ["Toallas", "Secador de pelo", "Artículos de aseo gratuitos"],
    numbeds: 2,
    pets: true,
    price: 500000,
    description: "Habitación doble estándar para dos personas.",
    numHabitacion: 1,
    id: 234,
    reserved: false,
    img: hotel1,
  },
  {
    name: "Habitación Doble Superior",
    bed: "Cama doble",
    capacityPeople: 1,
    roomView: "Vista al mar",
    services: ["Caja fuerte", "Aire acondicionado", "Minibar", "Jacuzzi"],
    modCons: [
      "Toallas",
      "Secador de pelo",
      "Artículos de aseo gratuitos",
      "Albornoz",
    ],
    numbeds: 2,
    pets: true,
    price: 800000,
    description:
      "Habitación doble superior con vista al mar y jacuzzi privado.",
    numHabitacion: 2,
    id: 2387,
    reserved: false,
    img: hotel3,
  },
  {
    name: "Habitación Familiar",
    bed: "2 camas dobles",
    capacityPeople: 2,
    roomView: "Vista a la piscina",
    services: [
      "Caja fuerte",
      "Aire acondicionado",
      "Minibar",
      "Televisión por cable",
    ],
    modCons: ["Toallas", "Secador de pelo", "Artículos de aseo gratuitos"],
    numbeds: 4,
    pets: true,
    price: 700000,
    description:
      "Habitación familiar para cuatro personas con dos camas dobles.",
    id: 3,
    reserved: false,
    img: hotel6,
  },
  {
    name: "Habitación Doble con Terraza",
    bed: "Cama doble",
    capacityPeople: 1,
    roomView: "Vista a la ciudad",
    services: ["Aire acondicionado", "Minibar", "Terraza"],
    modCons: ["Toallas", "Secador de pelo", "Artículos de aseo gratuitos"],
    numbeds: 2,
    pets: false,
    price: 650000,
    description: "Habitación doble con terraza privada.",
    id: 5,
    reserved: false,
    img: hotel9,
  },
  {
    name: "Habitación Triple Estándar",
    bed: "3 camas individuales",
    capacityPeople: 3,
    roomView: "Vista al jardín",
    services: [
      "Caja fuerte",
      "Aire acondicionado",
      "Minibar",
      "Televisión por cable",
    ],
    modCons: ["Toallas", "Secador de pelo", "Artículos de aseo gratuitos"],
    numbeds: 3,
    pets: false,
    price: 450000,
    description: "Habitación triple estándar para tres personas.",
    id: 6765,
    reserved: false,
    img: hotel12,
  },
  {
    name: "Habitación Doble con Acceso para Discapacitados",
    bed: "Cama doble",
    capacityPeople: 1,
    roomView: "Vista a la ciudad",
    services: ["Aire acondicionado", "Minibar", "Acceso para discapacitados"],
    modCons: [
      "Toallas",
      "Secador de pelo",
      "Artículos de aseo gratuitos",
      "Barras de agarre",
    ],
    numbeds: 2,
    pets: false,
    price: 560000,
    description: "Habitación doble con acceso para discapacitados.",
    id: 7465,
    reserved: false,
    img: hotel15,
  },
  {
    name: "Habitación Individual",
    bed: "Cama individual",
    capacityPeople: 1,
    roomView: "Vista a la ciudad",
    services: ["Aire acondicionado", "Minibar"],
    modCons: ["Toallas", "Secador de pelo", "Artículos de aseo gratuitos"],
    numbeds: 1,
    pets: false,
    price: 700000,
    description: "Habitación individual con cama individual.",
    id: 8234,
    reserved: false,
    img: hotel18,
  },
  {
    name: "Habitación Doble con Acceso para Discapacitados",
    bed: "Cama doble",
    capacityPeople: 1,
    roomView: "Vista a la ciudad",
    services: ["Aire acondicionado", "Minibar", "Acceso para discapacitados"],
    modCons: [
      "Toallas",
      "Secador de pelo",
      "Artículos de aseo gratuitos",
      "Barras de agarre",
    ],
    numbeds: 2,
    esFamiliar: false,
    includesBreakfast: true,
    price: 560000,
    description: "Habitación doble con acceso para discapacitados.",
    id: 734,
    reserved: false,
    img: hotel21,
  },
  {
    name: "Habitación Individual",
    bed: "Cama individual",
    capacityPeople: 1,
    roomView: "Vista a la ciudad",
    services: ["Aire acondicionado", "Minibar"],
    modCons: ["Toallas", "Secador de pelo", "Artículos de aseo gratuitos"],
    numbeds: 1,
    esFamiliar: false,
    includesBreakfast: true,
    price: 700000,
    description: "Habitación individual con cama individual.",
    id: 8564,
    reserved: false,
    img: hotel2,
  },
  {
    name: "Habitación Familiar con Balcón",
    bed: "Cama doble y 2 camas individuales",
    capacityPeople: 3,
    roomView: "Vista al mar",
    services: [
      "Caja fuerte",
      "Aire acondicionado",
      "Minibar",
      "Televisión por cable",
      "Balcón",
    ],
    modCons: [
      "Toallas",
      "Secador de pelo",
      "Artículos de aseo gratuitos",
      "Albornoz",
    ],
    numbeds: 4,
    esFamiliar: true,
    includesBreakfast: true,
    price: 800000,
    description:
      "Habitación familiar con balcón con vista al mar y capacidad para cuatro personas.",
    id: 965,
    reserved: false,
    img: hotel4,
  },
  {
    name: "Habitación Doble Superior",
    bed: "Cama king size",
    capacityPeople: 1,
    roomView: "Vista a la ciudad",
    services: [
      "Aire acondicionado",
      "Minibar",
      "Cafetera",
      "Botella de agua gratuita diaria",
    ],
    modCons: ["Toallas", "Secador de pelo", "Artículos de aseo gratuitos"],
    numbeds: 2,
    esFamiliar: false,
    includesBreakfast: true,
    price: 750000,
    description:
      "Habitación doble superior con cama king size y vista a la ciudad.",
    id: 1124,
    reserved: false,
    img: hotel6,
  },
  {
    name: "Habitación Familiar con Terraza",
    bed: "2 camas dobles",
    capacityPeople: 4,
    roomView: "Vista al jardín",
    services: [
      "Aire acondicionado",
      "Minibar",
      "Terraza",
      "Televisión por cable",
    ],
    modCons: [
      "Toallas",
      "Secador de pelo",
      "Artículos de aseo gratuitos",
      "Albornoz",
      "Zapatillas",
    ],
    numbeds: 4,
    includesBreakfast: true,
    price: 650000,
    description:
      "Habitación familiar con terraza privada y capacidad para cuatro personas.",
    id: 13452,
    reserved: false,
    img: hotel8,
  },
  {
    name: "Habitación Doble Deluxe",
    bed: "Cama king size",
    capacityPeople: 1,
    roomView: "Vista al mar",
    services: [
      "Caja fuerte",
      "Aire acondicionado",
      "Minibar",
      "Televisión por cable",
      "Balcón con vista al mar",
    ],
    modCons: [
      "Toallas",
      "Secador de pelo",
      "Artículos de aseo gratuitos",
      "Albornoz",
      "Zapatillas",
    ],
    numbeds: 2,
    includesBreakfast: true,
    price: 700000,
    description:
      "Habitación doble deluxe con cama king size y balcón con vista al mar.",
    id: 2313,
    reserved: false,
    img: hotel10,
  },
  {
    name: "Habitación Triple Superior",
    bed: "3 camas individuales",
    capacityPeople: 3,
    roomView: "Vista a la ciudad",
    services: [
      "Caja fuerte",
      "Aire acondicionado",
      "Minibar",
      "Televisión por cable",
      "Cafetera",
    ],
    modCons: ["Toallas", "Secador de pelo", "Artículos de aseo gratuitos"],
    numbeds: 3,
    includesBreakfast: true,
    price: 650000,
    description:
      "Habitación triple superior con tres camas individuales y vista a la ciudad.",
    id: 12314,
    reserved: false,
    img: hotel14,
  },
  {
    name: "Habitación Individual con Escritorio",
    bed: "Cama individual",
    capacityPeople: 1,
    roomView: "Vista a la ciudad",
    services: ["Aire acondicionado", "Minibar", "Escritorio"],
    modCons: ["Toallas", "Secador de pelo", "Artículos de aseo gratuitos"],
    numbeds: 1,
    includesBreakfast: true,
    price: 900000,
    description: "Habitación individual con cama individual y escritorio.",
    id: 1645,
    reserved: false,
    img: hotel16,
  },
  {
    name: "Habitación Familiar con Terraza",
    description: "2 camas dobles",
    capacityPeople: 4,
    roomView: "Vista al jardín",
    services: [
      "Aire acondicionado",
      "Minibar",
      "Terraza",
      "Televisión por cable",
    ],
    modCons: [
      "Toallas",
      "Secador de pelo",
      "Artículos de aseo gratuitos",
      "Albornoz",
      "Zapatillas",
    ],
    numbeds: 4,
    pets: true,
    price: 650000,
    description:
      "Habitación familiar con terraza privada y capacidad para cuatro personas.",
    id: 97812,
    reserved: false,
    img: hotel20,
  },
  {
    name: "Habitación Doble Deluxe",
    description: "Cama king size",
    capacityPeople: 1,
    roomView: "Vista al mar",
    services: [
      "Caja fuerte",
      "Aire acondicionado",
      "Minibar",
      "Televisión por cable",
      "Balcón con vista al mar",
    ],
    modCons: [
      "Toallas",
      "Secador de pelo",
      "Artículos de aseo gratuitos",
      "Albornoz",
      "Zapatillas",
    ],
    numbeds: 2,
    pets: true,
    price: 700000,
    description:
      "Habitación doble deluxe con cama king size y balcón con vista al mar.",
    id: 1783,
    reserved: false,
    img: hotel22,
  },
  {
    name: "Habitación Triple Superior",
    description: "3 camas individuales",
    capacityPeople: 3,
    roomView: "Vista a la ciudad",
    services: [
      "Caja fuerte",
      "Aire acondicionado",
      "Minibar",
      "Televisión por cable",
      "Cafetera",
    ],
    modCons: ["Toallas", "Secador de pelo", "Artículos de aseo gratuitos"],
    numbeds: 3,
    pets: true,
    price: 650000,
    description:
      "Habitación triple superior con tres camas individuales y vista a la ciudad.",
    id: 1644,
    reserved: false,
    img: hotel4,
  },
  {
    name: "Habitación Individual con Escritorio",
    description: "Cama individual",
    capacityPeople: 1,
    roomView: "Vista a la ciudad",
    services: ["Aire acondicionado", "Minibar", "Escritorio"],
    modCons: ["Toallas", "Secador de pelo", "Artículos de aseo gratuitos"],
    numbeds: 1,
    pets: true,
    price: 900000,
    description: "Habitación individual con cama individual y escritorio.",
    id: 1455,
    reserved: false,
    img: hotel2,
  },
  {
    name: "Habitación Individual con Baño Compartido",
    bed: "Cama individual",
    capacityPeople: 1,
    roomView: "Vista a la ciudad",
    services: ["Aire acondicionado", "Armario"],
    modCons: ["Toallas", "Secador de pelo", "Artículos de aseo gratuitos"],
    numbeds: 1,
    includesBreakfast: false,
    pets: true,
    price: 760000,
    description: "Habitación individual con cama individual y baño compartido.",
    id: 19243,
    reserved: false,
    img: hotel7,
  },
  {
    name: "Habitación Cuádruple Familiar",
    bed: "2 camas dobles",
    capacityPeople: 4,
    roomView: "Vista al jardín",
    services: [
      "Caja fuerte",
      "Aire acondicionado",
      "Minibar",
      "Televisión por cable",
      "Balcón con vista al jardín",
    ],
    modCons: [
      "Toallas",
      "Secador de pelo",
      "Artículos de aseo gratuitos",
      "Albornoz",
      "Zapatillas",
    ],
    numbeds: 4,
    includesBreakfast: true,
    pets: true,
    price: 600000,
    description:
      "Habitación cuádruple familiar con dos camas dobles y balcón con vista al jardín.",
    id: 20234,
    reserved: false,
    img: hotel11,
  },
  {
    name: "Habitación Doble con Terraza",
    bed: "Cama king size",
    capacityPeople: 2,
    roomView: "Vista al mar",
    services: [
      "Aire acondicionado",
      "Minibar",
      "Terraza",
      "Televisión por cable",
    ],
    modCons: [
      "Toallas",
      "Secador de pelo",
      "Artículos de aseo gratuitos",
      "Albornoz",
      "Zapatillas",
    ],
    numbeds: 2,
    includesBreakfast: false,
    pets: true,
    price: 500000,
    description:
      "Habitación doble con cama king size y terraza privada con vista al mar.",
    id: 22341,
    reserved: false,
    img: hotel13,
  },
  {
    name: "Habitación Triple con Baño Compartido",
    bed: "3 camas individuales",
    capacityPeople: 3,
    roomView: "Vista a la ciudad",
    services: ["Aire acondicionado", "Armario"],
    modCons: ["Toallas", "Secador de pelo", "Artículos de aseo gratuitos"],
    numbeds: 3,
    includesBreakfast: false,
    pets: true,
    price: 550000,
    description:
      "Habitación triple con tres camas individuales y baño compartido.",
    id: 2341,
    reserved: false,
    img: hotel19,
  },
];
